### ISSUE TITLE
Conversion to the ChatScript.

### ISSUE THREAD

**Issue by narnikgamarnikus** [bwilcox-1234/ChatScript#152]
Hello.

There is a need to create a convenient interaction between the form fields in the web interface and the ChatScript interpreter

That is, I want the user to use simple and understandable widgets, the contents of which would be converted into certain ChatScript's lexemes.

I just met ChatScript yesterday, but I really liked it, but I also understand that an average user will long understand how to use these specific symbols and constructions.

I want to ask the professionals who have long been familiar with ChatScript. Is there any sense in doing this, and if so, what should I take the first steps towards this goal?

Thank you very much in advance.

**Comment by solyaris** [comment]
Hi
I's suggest you to re-post your question here:
https://www.chatbots.org/ai_zone/viewforum/44/

and close the issue here instead (your question is not a software/bug issue);

About your design point, I feel that basically... it's pretty simple to use CS to convert a GUI (graphical UI) webform widgets to a CUI (conversational user interface) script. I suggest to study documentation in WIKI pages here. Just a gist: to manage an input data  form field, here a pseudo code:

```
#
#  get first name
#
u: FIRSTNAME ( !$firstname )

   What is your first name?

   a: ( ~helpinput ) 
   
      ^help_field(first_name) 
      ^respond(~.FIRSTNAME)

    #! Anna Lisa  $firstname = null
    #! George     $firstname = null
    #! Anna Maria $firstname = null

    a: ( _* ) 
       
       ^validate_firstname(_0) 
       

```
Hera above, just a possible way to manage a "required" field with a conversational strict loop...

Please close the issue here.
regards
giorgio
