### ISSUE TITLE
%user gives garbage value in server mode

### ISSUE THREAD

**Issue by ashokbarthwal** [bwilcox-1234/ChatScript#153]
when running chatscript in standalone mode it gives correct username using %user but in server mode, it gives some random numbers

**Comment by bwilcox-1234** [comment]
So I dont see any reason in code for this to be true. I did a simple test in windows using SERVER BATCH FILES localserver.bat and localclient.bat with a simple bot that sent back %user when asked. It worked fine. I would need more details to recreate.

**Comment by ashokbarthwal** [comment]
thanks for the reply but the problem is not with code problem is that you have not written any code in a web application in which the username we are providing is going to add in the facts as you have done in standalone. In web application you are using user name only to show in web page  ( js code in index.php i.e var name = $('#txtUser').val(); )

**Comment by bwilcox-1234** [comment]
the web application uses what the user gives as their name ONLY as a label for the text pane. The name passed to chatscript is their IP address, because user's name may not be unique. That applies to a purely public bot. If it is a bot in a restricted space with certified logins, then the web page would be modified to use the name provided from the login.

**Comment by ashokbarthwal** [comment]
thanks a lot for such detail explanation by the way i have solved that user name issue.
