### ISSUE TITLE
getRule returns Failrule with legit arguments

### ISSUE THREAD

**Issue by Tobi-La** [bwilcox-1234/ChatScript#157]
Hi, I have and issue in my code, which I am not able to reproduce yet.

I've debugged the code, but I am lacking knowledge to understand the problem.

My problem is that a call of
`getRule(TAG myTopic.0.0)`

returns FailRuleBit(2). If I remove a call to ^callstack that I have in my code before that, the issue disappears, so it seems to have something todo with the interaction between those too.

What I observed during debugging in static FunctionResult GetRuleCode(char* buffer):
`if (dot && IsDigit(dot[1])) rule = GetRuleTag(topicid,id,arg2);`

returns null.

I debugged this function a few levels and saw that:
`
topicid = FindTopicIDByName(tag);` returns 0

because 

`WORDP FindWord(const char* word, int len,uint64 caseAllowed`) 

returns and object where all 3 ids in x are 0.

Sorry for the complicated description, and I don't know how to proceed at this point

**Comment by bwilcox-1234** [comment]
getRule(TAG myTopic.0.0)  --- offhand myTOpic is not the name of a topic.  ~myTOpic is

**Comment by Tobi-La** [comment]
Sorry, I made this mistake by replacing my real topic name with this placeholder name. I have user the ~ in my code

**Comment by bwilcox-1234** [comment]
the only interaction I can think of is if the factset from ^callstack was > 10,000, and thus overflowed. I have set a protection against that in the future, but that is unlikely your problem.

**Comment by bwilcox-1234** [comment]
This simple test worked: 
outputmacro: ^test2( ^ms $_t2 ^myv)

 ^callstack(@0)
$_x = getRule(TAG ~INTRODUCTIONS.0.0)
$_x
outputmacro: ^test( $_t1 $_t2 $_t3)
^test2($_t1 $_t2 $_t3)
topic: ~INTRODUCTIONS keep repeat (~emogoodbye ~emohello ~emohowzit name here )
t: Greetings
u: (test _*1 _*1 _*1) ^test(_0 _1 _2 )

**Comment by Tobi-La** [comment]
After what felt like hundreds of hours of trying I finally managed to make a simple test for the issue.
It's a really weird one. 
The issue occurs if you have a topic which topic name is generated with join. There has to be an uppercase letter in the 2nd argument. Then the error occurs if you execute ^callstack in this topic.
Execute test1 with the following code example:

If you comment out ^callstack it's working. If you bring it back the rule is aborting with fail.

```
topic:  ~anotherTopic[]
u: TESTRULE (test1)
    ^getRule(TAG ~anotherTopic.0.0)
    ^callstack(@3)
    ^getRule(TAG ~anotherTopic.0.0)

topic: ~test keep repeat[ test1 test2]
u: (test1) $$_topicName = ^join(~another Topic)
            ^respond($$_topicName)
```

The second getRule doesn't have to be in the same rule, it behaves the same everywhere in the code after ^callstack as long as you're in the same volley.

**Comment by bwilcox-1234** [comment]
OK> very entertainig and I have fixed it.  Here is what happens:  Internally all functions and concept names are always stored in lower case. Script compiler does that. System dictionary assumes that. You synthesized a name which had mixed case but doesnt automatically go into the dictionary. But when you call callstack it tries to make a name for the facts and THAT stores it into the dictionary. Since the store routine "knows" all concept names are lower case, it doesnt check the casing and doesnt mark the word as having uppercase letters. So now you have 2 entries in the dictionary, one with mixed casing. Your call to getrule requests finding the topic. Getrule knows casing must be lowercase, so it takes your request and converts to lower case, then asks the dictionary for it. Dictionary first finds your mixed case entry and returns that. It is not a topic, hence getrule fails.  You can temporarily fix your code to not have uppercase in your topic names.  Next release will enforce rules better.

**Comment by Tobi-La** [comment]
It was enough to use lowercase letters in my ^join, thank you very much Bruce :)
