### ISSUE TITLE
weird output with 7.111

### ISSUE THREAD

**Issue by ludan-av** [bwilcox-1234/ChatScript#40]
I installed 7.111 on my local computer: Windows OS.
Rebuilt my bot and tested - everything is OK.

Then I installed 7.111 on my Linux server.
I copied the TOPIC folder from my local Windows to this Linux server - that's what I usually do.

When I run 7.111 on this Linux server, I get these responses:
B(^alttopics 0
(INPUT B(^alttopics 1 B(^alttopics 2
etc.

That's not good.

I reverted my server from 7.111 to 7.1. I did not change the TOPIC folder and I still get these weird outputs.

When I overwrite the TOPIC folder with a bot build with 7.1, everything is back fine.

**Comment by kuzyn** [comment]
I would not recommend moving your TOPIC folder from/to different environment. Furthermore, there is no need for it since these files can be easily generated.

If you `:build` 0 then `:build _you-bot-name_` both on your local machine and on your server, you will end up with a similar TOPIC folder, but one that was compiled on that particular environment. Interchanging them might have worked before if there was no engine change that affected the compilation process in the envs.

Can you recompile on the server and try again? Better again, before compiling, run `NON-WINDOWS NON-C/LINUX/clean-files.sh`

**Comment by ludan-av** [comment]
Works with a fresh compile on Linux from sources.

It is indeed a better practice to compile on a new platform.

Thanks!
