### ISSUE TITLE
Mac build 6.8 not working

### ISSUE THREAD

**Issue by dvulanov** [bwilcox-1234/ChatScript#9]
```
SRC/mongodb.cpp:23:10: fatal error: 'bson.h' file not found
#include "bson.h"
         ^
1 error generated.
```

bson.h is located in SRC/mongo/bson/

**Comment by hiteshsaraf** [comment]
faced a similar issue when making mongo server on linux. The problem was "bson" and "mongoc" files have to come from the linux file system itself and not from the SRC folders. bson comes along with mongoc, so probably you need to install bson and mongoc on your proper mac folders.
That worked for us on linux.
